/* Generated By:JJTree: Do not edit this line. ASTfields.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mars;

public
class ASTfields extends SimpleNode {
  public ASTfields(int id) {
    super(id);
  }

  public ASTfields(Jsql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1260191d9a7821d6391392178c6c2b71 (do not edit this line) */
