/* Generated By:JJTree: Do not edit this line. ASTfieldId.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mars;

public
class ASTfieldId extends SimpleNode {
  public ASTfieldId(int id) {
    super(id);
  }

  public ASTfieldId(Jsql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aa4524eaf0917586cdbbd901d5a90f73 (do not edit this line) */
