/* Generated By:JJTree: Do not edit this line. ASTjsql.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mars;

public
class ASTjsql extends SimpleNode {
  public ASTjsql(int id) {
    super(id);
  }

  public ASTjsql(Jsql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b1ea29178e53a7859460660336a64484 (do not edit this line) */
