/* Generated By:JJTree: Do not edit this line. ASTstart.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mars;

public
class ASTstart extends SimpleNode {
  public ASTstart(int id) {
    super(id);
  }

  public ASTstart(Jsql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d0f7ef739407885d5c9b435e57d486e9 (do not edit this line) */
