/* Generated By:JJTree: Do not edit this line. ASTselect.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mars;

public
class ASTselect extends SimpleNode {
  public ASTselect(int id) {
    super(id);
  }

  public ASTselect(Jsql p, int id) {
    super(p, id);
  }

  public final void process() {
  }
}
/* JavaCC - OriginalChecksum=c1879c35398c74b493ae5f1e6fa59bf1 (do not edit this line) */
