/* Generated By:JJTree: Do not edit this line. ASTsql.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mars;

public
class ASTsql extends SimpleNode {
  public ASTsql(int id) {
    super(id);
  }

  public ASTsql(Jsql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=18f8b28b741c88b3fab4ad53c0d924ce (do not edit this line) */
