/* Generated By:JJTree: Do not edit this line. ASTtableId.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mars;

public
class ASTtableId extends SimpleNode {
  public ASTtableId(int id) {
    super(id);
  }

  public ASTtableId(Jsql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4d2ec29c629ea5a9ac85eb94f51bb45e (do not edit this line) */
