/* Generated By:JJTree: Do not edit this line. ASTtables.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mars;

public
class ASTtables extends SimpleNode {
  public ASTtables(int id) {
    super(id);
  }

  public ASTtables(Jsql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b5f27ea4738094cb2ddc447520cd908 (do not edit this line) */
