/* Generated By:JJTree&JavaCC: Do not edit this line. JsqlConstants.java */
package org.mars;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JsqlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int FROM = 6;
  /** RegularExpression Id. */
  int WHERE = 7;
  /** RegularExpression Id. */
  int INSERT = 8;
  /** RegularExpression Id. */
  int INTO = 9;
  /** RegularExpression Id. */
  int VALUES = 10;
  /** RegularExpression Id. */
  int ORDER = 11;
  /** RegularExpression Id. */
  int BY = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int EQ = 16;
  /** RegularExpression Id. */
  int NE = 17;
  /** RegularExpression Id. */
  int LT = 18;
  /** RegularExpression Id. */
  int GT = 19;
  /** RegularExpression Id. */
  int LE = 20;
  /** RegularExpression Id. */
  int GE = 21;
  /** RegularExpression Id. */
  int LP = 22;
  /** RegularExpression Id. */
  int RP = 23;
  /** RegularExpression Id. */
  int NUMBER = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;
  /** RegularExpression Id. */
  int NSIGN = 26;
  /** RegularExpression Id. */
  int ID = 27;
  /** RegularExpression Id. */
  int LETTER = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "\"insert\"",
    "\"into\"",
    "\"values\"",
    "\"order\"",
    "\"by\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"(\"",
    "\")\"",
    "<NUMBER>",
    "<DIGIT>",
    "<NSIGN>",
    "<ID>",
    "<LETTER>",
    "\";\"",
    "\",\"",
  };

}
