/* Generated By:JavaCC: Do not edit this line. JsqlTreeConstants.java Version 6.1_2 */
package org.mars;

public interface JsqlTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;


  public String[] jjtNodeName = {
    "start",
    "void",
  };
}
/* JavaCC - OriginalChecksum=5fb6d01ff030e341db87d0943406a71d (do not edit this line) */
