/* Generated By:JavaCC: Do not edit this line. JsqlTreeConstants.java Version 6.1_2 */
package org.mars;

public interface JsqlTreeConstants
{
  public int JJTSQL = 0;
  public int JJTSELECT = 1;
  public int JJTFIELDS = 2;
  public int JJTFIELDID = 3;
  public int JJTTABLES = 4;
  public int JJTTABLEID = 5;


  public String[] jjtNodeName = {
    "sql",
    "select",
    "fields",
    "fieldId",
    "tables",
    "tableId",
  };
}
/* JavaCC - OriginalChecksum=5c72e66ac8eb9e560d2ccef8846aebfd (do not edit this line) */
